### ISSUE TITLE
Replace the broken travis.ci with an Github Action

### ISSUE THREAD

**Issue by KeyboardInterrupt** [KeyboardInterrupt/awesome-ansible#26]
The `travis.ci` pipeline is broken, we should add a Github Action to replace it.

Q: Are there any great Actions for awesome lists, like Markdown Linters and stuff?

**Comment by xoxys** [comment]
Maybe you want to take a look at Drone CI (cloud.drone.io) as an alternative to GH Actions. I'm using it for my projects and could help to set it up if you like. If you want to see it in action you can take  a look at some of my projects: https://github.com/xoxys/ansible-later/blob/master/.drone.yml#L352. I'm using e.g. markdownlint for my Hugo project documentations.

**Comment by KeyboardInterrupt** [comment]
Thank you for the kind offer, I wanted to play around with Github actions though to get a feel for them.

I had to make lots of changes to the README.md to adhere to the `awesome-linter` which just shows how important it is to have this step of linting automated away ^^.  #29 

Having the Linting/Pipelines within GitHub, with no dependency to i.E. Travis or Circle, should theoretically allow anyone forking the repository to run and modify the workflows/actions in their respective fork, without a dependency to an external service.

**Comment by xoxys** [comment]
Sure, whatever works for you :) In my case I explicitly wanted the decoupling because I have a private Gitea server running and I wanted a git server independent CI system.
